version: '3.1'

services:
    webserver:
        build: .
        restart: always
        ports: 
            - 8080:80
        environment:
            PHP_EXTENSION_XDEBUG: 1
            WORDPRESS_DB_HOST: db 
            WORDPRESS_DB_USER: nirina
            WORDPRESS_DB_PASSWORD: moissons
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini

    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: nirina
            MYSQL_PASSWORD: moissons
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./db:/var/lib/mysql
            - ./schema:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8081:80
