version: '3.1'

services:
    wordpress:
        image: wordpress
        container_name: wp-servitel
        ports: 
            - 9000:80  # Port modifié pour WordPress
        environment:
            WORDPRESS_DB_HOST: db 
            WORDPRESS_DB_USER: nirina
            WORDPRESS_DB_PASSWORD: moissons
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./wordpress:/var/www/html

    db: 
        image: mysql:5.7
        container_name: db-servitel
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: nirina
            MYSQL_PASSWORD: moissons
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./db:/var/lib/mysql
            - ./schema:/docker-entrypoint-initdb.d
        ports:
            - 1036:3306  # Port modifié pour MySQL

    phpmyadmin:
        image: phpmyadmin
        container_name: ppa-servitel
        ports:
            - 1081:80  # Port modifié pour phpMyAdmin

volumes:
    wordpress:
    db:
